### ISSUE TITLE
403 Denied  

### ISSUE THREAD

**Issue by 0x587669** [i2p/i2p.i2p#10]
403 Denied

Inproxy access denied. You must run I2P to access this site.

I get that message on http://plugins.i2p/, http://forum.i2p/ and some others how ever other ones work like http://pastethis.i2p http://killyourtv.i2p/ and some others so what is the issue here, can any one help? P.S thanks for i2p fucking love it!

**Comment by 0x587669** [comment]
edit: 

forum.i2p is just down,

503 Service Unavailable

This I2P website is unavailable. It may be down or undergoing maintenance.

**Comment by user2p** [comment]
You have not configured your browser correctly if you are getting the "Inproxy access denied" message.This one means that you are NOT using i2p to connect to these sites.Your browser does not know that you want it to connect to these sites anonymously by using i2p.You must tell your browser to connect through i2p, by configuring your browser's proxy settings accordingly (by default host 127.0.0.1 and port 4444) 

    0x587669 <notifications@github.com> schrieb am 23:38 Freitag, 12.Februar 2016:
 

 403 DeniedInproxy access denied. You must run I2P to access this site.I get that message on http://plugins.i2p/, http://forum.i2p/ and some others how ever other ones work like http://pastethis.i2p http://killyourtv.i2p/ and some others so what is the issue here, can any one help? P.S thanks for i2p fucking love it!—
